version: "3.7"
services:

  db:
    container_name: mysql57
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - "my_datavolume:/var/lib/mysql:rw"
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD:

#  adminer:
#    container_name: adminer
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

volumes:
  my_datavolume: {}

